### ISSUE TITLE
The BLT provided "openmp" pseudotarget doesn't (always) pass the correct openMP fortran flags

### ISSUE THREAD

**Issue by gzagaris** [LLNL/blt#175]
The "openmp" pseudotarget assumes that the OpenMP Fortran Flags are the same as C/C++ compiler flags.

We register the "openmp" pseudotarget as follows:
```
#################################################
# OpenMP
# (OpenMP support is provided by the compiler)
#################################################
message(STATUS "OpenMP Support is ${ENABLE_OPENMP}")
if(ENABLE_OPENMP)
    find_package(OpenMP REQUIRED)
    message(STATUS "OpenMP CXX Flags: ${OpenMP_CXX_FLAGS}")
    
    # register openmp with blt
    blt_register_library(NAME openmp
                         COMPILE_FLAGS ${OpenMP_CXX_FLAGS} 
                         LINK_FLAGS    ${OpenMP_CXX_FLAGS} )
endif()
```

This works for the most part, as long as:
* The C++ language is enabled
* The C++ and Fortran OpenMP flags match 

The latter may not always be the case. For example, for a project that uses Clang for C/C++ in conjunction with GNU Fortran, CMake will compute the following flags:

```
//C++ compiler flags for OpenMP parallization
OpenMP_CXX_FLAGS:STRING=-fopenmp=libomp

//C compiler flags for OpenMP parallization
OpenMP_C_FLAGS:STRING=-fopenmp=libomp

//Fortran compiler flags for OpenMP parallization
OpenMP_Fortran_FLAGS:STRING=-fopenmp
```

But, when building an executable like this:
```
blt_add_executable(
    NAME foo
    SOURCES foo.F
    DEPENDS_ON  openmp
    )
```

This would pass `OpenMP_CXX_FLAGS`, leading to the following compiler error:
```
gfortran: error: unrecognized command line option '-fopenmp=libomp'
```

Perhaps, BLT should register two pseudo libraries/targets for C/C++ and Fortran respectively, like this:
```
if(ENABLE_OPENMP)
    find_package(OpenMP REQUIRED)
    message(STATUS "OpenMP CXX Flags: ${OpenMP_CXX_FLAGS}")
    
    # register openmp with blt
    blt_register_library(NAME openmp-cxx
                         COMPILE_FLAGS ${OpenMP_CXX_FLAGS} 
                         LINK_FLAGS    ${OpenMP_CXX_FLAGS} )

   if ( ENABLE_FORTRAN)
      blt_register_library(NAME openmp-fortran
                                       COMPILE_FLAGS ${OpenMP_Fortran_FLAGS}
                                       LINK_FLAGS ${OpenMP_Fortran_FLAGS} )
  endif()

endif()
```

This would at least make it more explicit to the application using this about how things are compiled/linked. Or alternatively, come up with a way to make it easier for an application to set source file properties for OpenMP. The latter may allow the most flexibility and be less clunky.

**Comment by kennyweiss** [comment]
@gzagaris -- we have the capability in our ``blt_append_custom_compiler_flag`` macro to distinguish between the CXX compiler and the Fortran compiler for the mixed compilers use case (via the ``LANGUAGE`` parameter).

Does ``find_package(OpenMP)`` return the correct openmp flags for all compilers when using mixed compilers (e.g. clang + gfortran)?  Or would we need to explicitly define the flags in this use case?

**Comment by gzagaris** [comment]
@kennyweiss , yes, `find_package(OpenMP)` returns the correct flags (as indicated above). The problems is that our `blt_register_library` call for `openmp` only accounts (or assumes) that `{OpenMP_CXX_FLAGS}` holds the same flags as `{OpenMP_Fortran_FLAGS}`.  I am not sure if `blt_append_custom_compiler_flags` is the solution, but, it may be part of the solution here.

**Comment by davidbeckingsale** [comment]
I think this is fixed by #190

**Comment by gzagaris** [comment]
Unfortunately the generator expressions do not seem to work as advertised. This is still an issue.

**Comment by cyrush** [comment]
Is this the symptom:
```
-- Configuring done
CMake Error at CMakeLists.txt:82 (target_link_libraries):
  Error evaluating generator expression:
    $<COMPILE_LANGUAGE:Fortran>
  $<COMPILE_LANGUAGE:...> Unknown language.
-- Generating done
```

```
I/usr/WS2/larsen30/ascent_build/ascent/uberenv_libs/spack/opt/spack/linux-rhel7-x86_64/gcc-4.9.3/zlib-1.2.11-3r4cfkmx3wwfqeof4bc244yduu2mz4ur/include;\$<\$<NOT:\$<COMPILE_LANGUAGE:Fortran>>:-fopenmp>;\$<\$<COMPILE_LANGUAGE:Fortran>:-fopenmp>"
```

**Comment by gzagaris** [comment]
@cyrush, I think this is a separate issue. What I am seeing is this:
```
gfortran: error: unrecognized command line option '-fopenmp=libomp'
```

@rblake-llnl in #190 pointed out a link to a CMake patch for the symptom you mentioned, so, it may be fixed in a later version of CMake. See https://gitlab.kitware.com/FloopCZ/cmake/commit/4f82199befee194aa924fd4dcdb2f4aad1f7dab6

**Comment by rblake-llnl** [comment]
I just looked into writing generator expressions for the linking flags-- generator expressions don't work with `set_target_properties(... LINK_FLAGS ...)` which is what BLT uses in `blt_add_target_link_flags` in `BLTMacros.cmake`.  We could change that call to `target_link_libraries` which DOES support generator expressions, but I'm unsure if that would break existing code by subtly changing the linking line for complicated projects.

Pinging @cyrush because he's the last person that touched that line of code in `BLTMacros.cmake`

**Comment by rblake-llnl** [comment]
Does #206 fix the problem?

**Comment by gzagaris** [comment]
I have a fix for this in #317
